import sys

if sys.version_info >= (3, 12):
    from collections.abc import Buffer
else:
    from typing_extensions import Buffer

CYRX_FLAG_DEFAULT: int = ...
CYRX_FLAG_LARGE_PAGES: int = ...
CYRX_FLAG_HARD_AES: int = ...
CYRX_FLAG_FULL_MEM: int = ...
CYRX_FLAG_JIT: int = ...
CYRX_FLAG_SECURE: int = ...
CYRX_FLAG_ARGON2_SSSE3: int = ...
CYRX_FLAG_ARGON2_AVX2: int = ...
CYRX_FLAG_ARGON2: int = ...
CYRX_FLAG_V2: int = ...

def get_flags() -> int: ...
def dataset_item_count() -> int: ...

class Cache:
    def __init__(self, flags: int = 0): ...
    def init(self, key: Buffer) -> None: ...
    def get_memory(self) -> bytes: ...

class Dataset:
    def __init__(self, flags: int = 0): ...
    def init(self, cache: Cache, start_item: int, item_count: int) -> None:
        ...
    def get_memory(self) -> bytes: ...

class VM:
    def __init__(
        self, flags: int = 0, cache: Cache | None = None, dataset: Dataset | None = None
    ) -> None: ...
    def set_cache(self, cache: Cache) -> None: ...
    def set_dataset(self, dataset: Dataset) -> None: ...
    def hash(self, input: object) -> bytes: ...
    def hash_first(self, input: object) -> None: ...
    def hash_next(self, input: object) -> bytes: ...
    def hash_last(self) -> bytes: ...

class RXMiner:
    def __init__(
        self,
        threads: int = ...,
        large_pages: bool = ...,
        jit: bool = ...,
        secure: bool = ...,
        ssse3: bool = ...,
        avx2: bool = ...,
        argon2: bool = ...,
        v2: bool = ...,
    ) -> None: ...
    def run(self, data: Buffer, seed: Buffer) -> bytes: ...
